// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directory_content.proto

package org.es.network;

public final class DirectotyContentProtos {
  private DirectotyContentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtoFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string path = 2;
    boolean hasPath();
    String getPath();
    
    // required .network.ProtoFile.FileType type = 3;
    boolean hasType();
    org.es.network.DirectotyContentProtos.ProtoFile.FileType getType();
    
    // required int32 size = 4;
    boolean hasSize();
    int getSize();
  }
  public static final class ProtoFile extends
      com.google.protobuf.GeneratedMessage
      implements ProtoFileOrBuilder {
    // Use ProtoFile.newBuilder() to construct.
    private ProtoFile(Builder builder) {
      super(builder);
    }
    private ProtoFile(boolean noInit) {}
    
    private static final ProtoFile defaultInstance;
    public static ProtoFile getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtoFile getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.es.network.DirectotyContentProtos.internal_static_network_ProtoFile_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.es.network.DirectotyContentProtos.internal_static_network_ProtoFile_fieldAccessorTable;
    }
    
    public enum FileType
        implements com.google.protobuf.ProtocolMessageEnum {
      DIRECTORY(0, 0),
      FILE(1, 1),
      VIDEO(2, 2),
      ;
      
      public static final int DIRECTORY_VALUE = 0;
      public static final int FILE_VALUE = 1;
      public static final int VIDEO_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static FileType valueOf(int value) {
        switch (value) {
          case 0: return DIRECTORY;
          case 1: return FILE;
          case 2: return VIDEO;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<FileType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FileType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
              public FileType findValueByNumber(int number) {
                return FileType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.es.network.DirectotyContentProtos.ProtoFile.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final FileType[] VALUES = {
        DIRECTORY, FILE, VIDEO, 
      };
      
      public static FileType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private FileType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:network.ProtoFile.FileType)
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string path = 2;
    public static final int PATH_FIELD_NUMBER = 2;
    private java.lang.Object path_;
    public boolean hasPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          path_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .network.ProtoFile.FileType type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private org.es.network.DirectotyContentProtos.ProtoFile.FileType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.es.network.DirectotyContentProtos.ProtoFile.FileType getType() {
      return type_;
    }
    
    // required int32 size = 4;
    public static final int SIZE_FIELD_NUMBER = 4;
    private int size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSize() {
      return size_;
    }
    
    private void initFields() {
      name_ = "";
      path_ = "";
      type_ = org.es.network.DirectotyContentProtos.ProtoFile.FileType.DIRECTORY;
      size_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, size_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, size_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.es.network.DirectotyContentProtos.ProtoFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.es.network.DirectotyContentProtos.ProtoFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.es.network.DirectotyContentProtos.internal_static_network_ProtoFile_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.es.network.DirectotyContentProtos.internal_static_network_ProtoFile_fieldAccessorTable;
      }
      
      // Construct using org.es.network.DirectotyContentProtos.ProtoFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.es.network.DirectotyContentProtos.ProtoFile.FileType.DIRECTORY;
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.es.network.DirectotyContentProtos.ProtoFile.getDescriptor();
      }
      
      public org.es.network.DirectotyContentProtos.ProtoFile getDefaultInstanceForType() {
        return org.es.network.DirectotyContentProtos.ProtoFile.getDefaultInstance();
      }
      
      public org.es.network.DirectotyContentProtos.ProtoFile build() {
        org.es.network.DirectotyContentProtos.ProtoFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.es.network.DirectotyContentProtos.ProtoFile buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.es.network.DirectotyContentProtos.ProtoFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.es.network.DirectotyContentProtos.ProtoFile buildPartial() {
        org.es.network.DirectotyContentProtos.ProtoFile result = new org.es.network.DirectotyContentProtos.ProtoFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.es.network.DirectotyContentProtos.ProtoFile) {
          return mergeFrom((org.es.network.DirectotyContentProtos.ProtoFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.es.network.DirectotyContentProtos.ProtoFile other) {
        if (other == org.es.network.DirectotyContentProtos.ProtoFile.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPath()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              path_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.es.network.DirectotyContentProtos.ProtoFile.FileType value = org.es.network.DirectotyContentProtos.ProtoFile.FileType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              size_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string path = 2;
      private java.lang.Object path_ = "";
      public boolean hasPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
        return this;
      }
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      void setPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
      }
      
      // required .network.ProtoFile.FileType type = 3;
      private org.es.network.DirectotyContentProtos.ProtoFile.FileType type_ = org.es.network.DirectotyContentProtos.ProtoFile.FileType.DIRECTORY;
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.es.network.DirectotyContentProtos.ProtoFile.FileType getType() {
        return type_;
      }
      public Builder setType(org.es.network.DirectotyContentProtos.ProtoFile.FileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.es.network.DirectotyContentProtos.ProtoFile.FileType.DIRECTORY;
        onChanged();
        return this;
      }
      
      // required int32 size = 4;
      private int size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSize() {
        return size_;
      }
      public Builder setSize(int value) {
        bitField0_ |= 0x00000008;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        size_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:network.ProtoFile)
    }
    
    static {
      defaultInstance = new ProtoFile(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:network.ProtoFile)
  }
  
  public interface ProtoDirContentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .network.ProtoFile file = 1;
    java.util.List<org.es.network.DirectotyContentProtos.ProtoFile> 
        getFileList();
    org.es.network.DirectotyContentProtos.ProtoFile getFile(int index);
    int getFileCount();
    java.util.List<? extends org.es.network.DirectotyContentProtos.ProtoFileOrBuilder> 
        getFileOrBuilderList();
    org.es.network.DirectotyContentProtos.ProtoFileOrBuilder getFileOrBuilder(
        int index);
  }
  public static final class ProtoDirContent extends
      com.google.protobuf.GeneratedMessage
      implements ProtoDirContentOrBuilder {
    // Use ProtoDirContent.newBuilder() to construct.
    private ProtoDirContent(Builder builder) {
      super(builder);
    }
    private ProtoDirContent(boolean noInit) {}
    
    private static final ProtoDirContent defaultInstance;
    public static ProtoDirContent getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtoDirContent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.es.network.DirectotyContentProtos.internal_static_network_ProtoDirContent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.es.network.DirectotyContentProtos.internal_static_network_ProtoDirContent_fieldAccessorTable;
    }
    
    // repeated .network.ProtoFile file = 1;
    public static final int FILE_FIELD_NUMBER = 1;
    private java.util.List<org.es.network.DirectotyContentProtos.ProtoFile> file_;
    public java.util.List<org.es.network.DirectotyContentProtos.ProtoFile> getFileList() {
      return file_;
    }
    public java.util.List<? extends org.es.network.DirectotyContentProtos.ProtoFileOrBuilder> 
        getFileOrBuilderList() {
      return file_;
    }
    public int getFileCount() {
      return file_.size();
    }
    public org.es.network.DirectotyContentProtos.ProtoFile getFile(int index) {
      return file_.get(index);
    }
    public org.es.network.DirectotyContentProtos.ProtoFileOrBuilder getFileOrBuilder(
        int index) {
      return file_.get(index);
    }
    
    private void initFields() {
      file_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getFileCount(); i++) {
        if (!getFile(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < file_.size(); i++) {
        output.writeMessage(1, file_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < file_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, file_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.es.network.DirectotyContentProtos.ProtoDirContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.es.network.DirectotyContentProtos.ProtoDirContent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.es.network.DirectotyContentProtos.ProtoDirContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.es.network.DirectotyContentProtos.internal_static_network_ProtoDirContent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.es.network.DirectotyContentProtos.internal_static_network_ProtoDirContent_fieldAccessorTable;
      }
      
      // Construct using org.es.network.DirectotyContentProtos.ProtoDirContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (fileBuilder_ == null) {
          file_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fileBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.es.network.DirectotyContentProtos.ProtoDirContent.getDescriptor();
      }
      
      public org.es.network.DirectotyContentProtos.ProtoDirContent getDefaultInstanceForType() {
        return org.es.network.DirectotyContentProtos.ProtoDirContent.getDefaultInstance();
      }
      
      public org.es.network.DirectotyContentProtos.ProtoDirContent build() {
        org.es.network.DirectotyContentProtos.ProtoDirContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.es.network.DirectotyContentProtos.ProtoDirContent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.es.network.DirectotyContentProtos.ProtoDirContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.es.network.DirectotyContentProtos.ProtoDirContent buildPartial() {
        org.es.network.DirectotyContentProtos.ProtoDirContent result = new org.es.network.DirectotyContentProtos.ProtoDirContent(this);
//        int from_bitField0_ = bitField0_;
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            file_ = java.util.Collections.unmodifiableList(file_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.file_ = file_;
        } else {
          result.file_ = fileBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.es.network.DirectotyContentProtos.ProtoDirContent) {
          return mergeFrom((org.es.network.DirectotyContentProtos.ProtoDirContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.es.network.DirectotyContentProtos.ProtoDirContent other) {
        if (other == org.es.network.DirectotyContentProtos.ProtoDirContent.getDefaultInstance()) return this;
        if (fileBuilder_ == null) {
          if (!other.file_.isEmpty()) {
            if (file_.isEmpty()) {
              file_ = other.file_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFileIsMutable();
              file_.addAll(other.file_);
            }
            onChanged();
          }
        } else {
          if (!other.file_.isEmpty()) {
            if (fileBuilder_.isEmpty()) {
              fileBuilder_.dispose();
              fileBuilder_ = null;
              file_ = other.file_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fileBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFileFieldBuilder() : null;
            } else {
              fileBuilder_.addAllMessages(other.file_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getFileCount(); i++) {
          if (!getFile(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.es.network.DirectotyContentProtos.ProtoFile.Builder subBuilder = org.es.network.DirectotyContentProtos.ProtoFile.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFile(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .network.ProtoFile file = 1;
      private java.util.List<org.es.network.DirectotyContentProtos.ProtoFile> file_ =
        java.util.Collections.emptyList();
      private void ensureFileIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          file_ = new java.util.ArrayList<org.es.network.DirectotyContentProtos.ProtoFile>(file_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.es.network.DirectotyContentProtos.ProtoFile, org.es.network.DirectotyContentProtos.ProtoFile.Builder, org.es.network.DirectotyContentProtos.ProtoFileOrBuilder> fileBuilder_;
      
      public java.util.List<org.es.network.DirectotyContentProtos.ProtoFile> getFileList() {
        if (fileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(file_);
        } else {
          return fileBuilder_.getMessageList();
        }
      }
      public int getFileCount() {
        if (fileBuilder_ == null) {
          return file_.size();
        } else {
          return fileBuilder_.getCount();
        }
      }
      public org.es.network.DirectotyContentProtos.ProtoFile getFile(int index) {
        if (fileBuilder_ == null) {
          return file_.get(index);
        } else {
          return fileBuilder_.getMessage(index);
        }
      }
      public Builder setFile(
          int index, org.es.network.DirectotyContentProtos.ProtoFile value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.set(index, value);
          onChanged();
        } else {
          fileBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFile(
          int index, org.es.network.DirectotyContentProtos.ProtoFile.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.set(index, builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFile(org.es.network.DirectotyContentProtos.ProtoFile value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.add(value);
          onChanged();
        } else {
          fileBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFile(
          int index, org.es.network.DirectotyContentProtos.ProtoFile value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.add(index, value);
          onChanged();
        } else {
          fileBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFile(
          org.es.network.DirectotyContentProtos.ProtoFile.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.add(builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFile(
          int index, org.es.network.DirectotyContentProtos.ProtoFile.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.add(index, builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFile(
          java.lang.Iterable<? extends org.es.network.DirectotyContentProtos.ProtoFile> values) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          super.addAll(values, file_);
          onChanged();
        } else {
          fileBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        return this;
      }
      public Builder removeFile(int index) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.remove(index);
          onChanged();
        } else {
          fileBuilder_.remove(index);
        }
        return this;
      }
      public org.es.network.DirectotyContentProtos.ProtoFile.Builder getFileBuilder(
          int index) {
        return getFileFieldBuilder().getBuilder(index);
      }
      public org.es.network.DirectotyContentProtos.ProtoFileOrBuilder getFileOrBuilder(
          int index) {
        if (fileBuilder_ == null) {
          return file_.get(index);  } else {
          return fileBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.es.network.DirectotyContentProtos.ProtoFileOrBuilder> 
           getFileOrBuilderList() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(file_);
        }
      }
      public org.es.network.DirectotyContentProtos.ProtoFile.Builder addFileBuilder() {
        return getFileFieldBuilder().addBuilder(
            org.es.network.DirectotyContentProtos.ProtoFile.getDefaultInstance());
      }
      public org.es.network.DirectotyContentProtos.ProtoFile.Builder addFileBuilder(
          int index) {
        return getFileFieldBuilder().addBuilder(
            index, org.es.network.DirectotyContentProtos.ProtoFile.getDefaultInstance());
      }
      public java.util.List<org.es.network.DirectotyContentProtos.ProtoFile.Builder> 
           getFileBuilderList() {
        return getFileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.es.network.DirectotyContentProtos.ProtoFile, org.es.network.DirectotyContentProtos.ProtoFile.Builder, org.es.network.DirectotyContentProtos.ProtoFileOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.es.network.DirectotyContentProtos.ProtoFile, org.es.network.DirectotyContentProtos.ProtoFile.Builder, org.es.network.DirectotyContentProtos.ProtoFileOrBuilder>(
                  file_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:network.ProtoDirContent)
    }
    
    static {
      defaultInstance = new ProtoDirContent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:network.ProtoDirContent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_network_ProtoFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_ProtoFile_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_network_ProtoDirContent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_ProtoDirContent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027directory_content.proto\022\007network\"\220\001\n\tP" +
      "rotoFile\022\014\n\004name\030\001 \002(\t\022\014\n\004path\030\002 \002(\t\022)\n\004" +
      "type\030\003 \002(\0162\033.network.ProtoFile.FileType\022" +
      "\014\n\004size\030\004 \002(\005\".\n\010FileType\022\r\n\tDIRECTORY\020\000" +
      "\022\010\n\004FILE\020\001\022\t\n\005VIDEO\020\002\"3\n\017ProtoDirContent" +
      "\022 \n\004file\030\001 \003(\0132\022.network.ProtoFileB(\n\016or" +
      "g.es.networkB\026DirectotyContentProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_network_ProtoFile_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_network_ProtoFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_network_ProtoFile_descriptor,
              new java.lang.String[] { "Name", "Path", "Type", "Size", },
              org.es.network.DirectotyContentProtos.ProtoFile.class,
              org.es.network.DirectotyContentProtos.ProtoFile.Builder.class);
          internal_static_network_ProtoDirContent_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_network_ProtoDirContent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_network_ProtoDirContent_descriptor,
              new java.lang.String[] { "File", },
              org.es.network.DirectotyContentProtos.ProtoDirContent.class,
              org.es.network.DirectotyContentProtos.ProtoDirContent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
